### ISSUE TITLE
ADE Module 

### ISSUE THREAD

**Issue by WilliamCrossSkymantics** [citygml4j/citygml4j#19]
I have an ADE schema utilized in my CityGML data that I would like to parse as part of my marshaling / unmarshaling process. I noticed that there seems to be two examples of defining an ADE schema within the library- either registering it as an ADEModule or parsing the cityObject's directly with a schemaHandler. 

How are these two approaches different? Is an ADE Module just a hand-written code wrapper around JAXB unmarshaled XSD classes? I also could not find any code examples showcasing how to register an ADE module into the Modules collection. Any help would be much appreciated.

**Comment by clausnagel** [comment]
There are two ways to consume ADE content. First, whenever citygml4j comes accross ADE features or properties in a CityGML dataset for which there is no JAXB binding, then the corresponding XML element is simply mapped to an `org.w3c.dom.Element` object and wrapped by an `ADEGenericElement`. The citygml4j class `FeatureProperty<?>` (and its derived classes) has a `getGenericADEElement()` method that returns the `ADEGenericElement` representing an ADE feature. Likewise, all citygml4j feature classes provide a `getGenericApplicationPropertyOf...()` method that returns a list of `ADEComponent` objects. `ADEGenericElement` is a subtype of `ADEComponent`, and thus you could query the ADE properties of the feature using this method.

So, you do not miss any ADE content when parsing the dataset. This is quite convenient and does not require any extra coding. However, it is now your job to parse and process the DOM element. The `Schema` class has some utility methods that might be helpful. A `Schema` represents the ADE XML Schema, and you can, for instance, use it to check whether an XML element is a feature, a geometry or a property element. A `Schema` is retrieved from the `SchemaHandler` mentioned in your post. But instead of manually parsing the DOM element, you could also use JAXB or another binding framework to automatically map the DOM element to something else. You can even use the citygml4j `JAXBUnmarshaller` and `JAXBMarshaller` to process parts of the DOM element. For example, if the DOM element represents an ADE feature which has a GML geometry, then you could map the XML element representing the GML geometry to a citygml4j geometry class using the `JAXBUnmarshaller`. This might be interesting if you have already written some general algorithms that take citygml4j objects as input.

When writing an ADE-enriched dataset using this first method, then it is your job to map your internal representation of your ADE data to a DOM element, wrap it by `ADEGenericElement` and use a corresponding setter method to assign it to a citygml4j feature or feature property.

There are several programming examples for this first method in the folder `handling_ade\generic`. However, despite of being very flexible, a major drawback of this first method is that the DOM elements stand next to the citygml4j object model, which hinders reusing code for ADE content. 

That was the main motivation for implementing a second approach. The general idea is that users can augment the predefined citygml4j classes with their own ADE classes. For instance, if your ADE XML Schema defines a feature type `<ade:Hospital>` that is derived from the CityGML type `<bldg:Building>`, then you would implement a class `Hospital` that extends the citygml4j class `Building`. So it automatically inherits from `Building` (e.g. you do not need extra code to assign appearances or generic attributes), and you can write code that can consume both predefined citygml4j classes and your ADE classes.

Now, since citygml4j uses JAXB for XML processing, you also (and first) need to derive JAXB classes from your ADE XML Schema. And then you have to implement a thin wrapper layer which maps the JAXB instances to your ADE classes and vice versa. The good news is that deriving the JAXB classes is done by the tool [ade-xjc](https://github.com/citygml4j/ade-xjc). Implementing the ADE classes requires manual coding. And for feature classes, for instance, you have to implement or override some methods like `calcBoundingBox` or `copy`. But there are a lot of utility classes for this purpose which hopefully help to reduce the overall efforts.

The ADE classes, the JAXB classes and the wrapper layer are then bundled to a so-called ADE module. ADE modules can be packaged into their own JAR and are registered at runtime with the citygml4j library. The core interface that an ADE module has to implement is `ADEContext`. Registering an ADE module is as easy as this:

```java
CityGMLContext context = CityGMLContext.getInstance();
ADEContext myADEContext = new MyADEContext();
context.registerADEContext(myADEContext);
```

(alternatively, you can use the plugin mechanism offered by Java to create an instance of your ADE context)

If you have successfully implemented and registered your ADE module, then when parsing a CityGML dataset citygml4j will automatically map ADE content to your ADE classes (no more code than the above three lines are required for this). And you can write code that works for the predefined citygml4j classes and your ADE classes alike.

An ADE module can also optionally provide walker classes for your ADE classes. I very much like the citygml4j walkers and use them a lot in my projects. If you implement ADE walkers and provide them in your ADE module, then they are automatically used by the predefined walkers to visit your ADE objects. 

I have implemented two examples for ADE modules for two real-world ADEs:

NoiseADE: https://github.com/citygml4j/noise-ade-citygml4j
EnergyADE: https://github.com/citygml4j/energy-ade-citygml4j

And there are programming examples for this second method in the folder `handling_ade\ade_context`.

Sorry, quite a lengthy answer. As you can see, both methods require some additional coding. Let me know if I can further assist you.

**Comment by WilliamCrossSkymantics** [comment]
Thank you for the quick reply, @clausnagel! Especially in my case, the more information the better 👍 

The way forward to implement what I need seems much more clear to me now. If I have any questions I will continue posting them in this thread. Thanks again!

**Comment by WilliamCrossSkymantics** [comment]
Hi @clausnagel , one more question, if you'll oblige. Going through your ADE examples, In the case of NoiseADE I can see you define an ADE feature here in your XSD:

`<xsd:element name="NoiseCityFurnitureSegment" type="NoiseCityFurnitureSegmentType" substitutionGroup="core:_CityObject"/>`

However, the constructors of this Class defined here


`
public NoiseCityFurnitureSegment() {
}
public NoiseCityFurnitureSegment(NoiseADEModule module)    { super(module); }
`
would result in a compile-time error, as AbstractCityObject only contains an empty constructor definition. This is also true of classes extending the AbstractOpening class- An attempt to use

`public PublicSafetyDoor(PublicSafetyADEModule module) {   super(module);    }`

would result in a compilation error, as AbstractOpening constructor expects a module of Type BuildingModule.

I can see you opted to use the default provided no argument constructors in your EnergyADE Module. What led you to use differing approaches in your ADE class implementations? I am sorry if the reasons seem axiomatic- I'm new to the GML standards, so my understanding of the conventions are limited.

**Comment by clausnagel** [comment]
There are few changes in the `master` branch of citygml4j which are already reflected in the `master` branch of the NoiseADE module but not in the EnergyADE module yet.

In the upcoming citygml4j 2.9, `AbstractFeature` will have a constructor taking a `Module` object as parameter. This constructor is already used by `NoiseCityFurnitureSegment` in the `master` branch. So, the compile error goes away if you compile against the `master` branch of citygml4j.

To have a stable enviroment, use the sources of citygml4j 2.8.1, NoiseADE 2.3.1 and EnergyADE master (there is not yet an official release of the EnergyADE module).
