### ISSUE TITLE
citygml2cityjson 

### ISSUE THREAD

**Issue by BrendaXx** [citygml4j/citygml4j#22]
Dear Claus, 

While converting the attached gml file 
[testBuilding_v2.txt](https://github.com/citygml4j/citygml4j/files/3422746/testBuilding_v2.txt) I get the following error: 
![test_buildingError](https://user-images.githubusercontent.com/16100293/61724763-e0bcfb00-ad6e-11e9-9410-5dfc63438588.JPG) 

It seems like it has trouble reading the measureAttribute  `<gen:measureAttribute name="min height surface"><gen:value uom="#m">18.47</gen:value></gen:measureAttribute>` 

The convertion does work when this line is either deleted or when the schema link is changed to version 1 instead of 2 .
`xmlns:gen="http://www.opengis.net/citygml/generics/1.0"` I was wondering why it would give this error, since the measureattribute is implemented in the schema?

Brenda

**Comment by clausnagel** [comment]
Fixed in 609e1fc213d97f36dc90434b766adab0e9d5fbd2. Not an easy one, so thanks for reporting this bug and for pointing me to `gen:measureAttribute` as potential source of error. This helped a lot. I will release a new version of citygml4j containing the fix soon. Please use the `master` branch in the meantime or build citygml4j on your own (see [here](https://github.com/citygml4j/citygml4j#building)).

**Comment by BrendaXx** [comment]
Great, thanks for the quick response!

**Comment by clausnagel** [comment]
Just released [v2.10.2](https://github.com/citygml4j/citygml4j/releases/tag/v2.10.2) which contains the bugfix.
