### ISSUE TITLE
Add opening geometry to multiple wall surfaceMembers

### ISSUE THREAD

**Issue by fredpeertje** [citygml4j/citygml4j#27]
Hi Clausnagel,

I’m trying to add opening geometries (window or door) to an already existing LOD2 CityGML model. However, it commonly occurs that an opening geometry intersects with two or more exterior polygons. As interior polygons define openings in an exterior polygon, they have to be completely included in the area defined by the exterior polygon (see the figure below: Correct interior polygon (left) and incorrect interior polygon (right)).

<img width="894" alt="exterioropening" src="https://user-images.githubusercontent.com/64864465/91160690-04691800-e6ca-11ea-90c6-4361d196beb7.png">

In this case, a part of the intersecting opening geometry is simply placed over a wall surface and not integrated into the building.

How can I properly include opening geometries to a (complex) LOD2 model?

**Comment by fredpeertje** [comment]
Here an example of windows improperly added to a LOD2 building of a CityGML file.

[lod3_error.txt](https://github.com/citygml4j/citygml4j/files/5123022/lod3_error.txt)

**Comment by clausnagel** [comment]
Hi @fredpeertje, this is a general CityGML question rather than a citygml4j question. 

Here is a quote from the [CityGML 2.0 specification document](https://portal.opengeospatial.org/files/?artifact_id=47842) (chapter 10.3.3, p. 69): 
> If the geometric location of _Openings topologically lies within a surface component (e.g. gml:Polygon) of the gml:MultiSurface geometry, these _Openings must be represented as holes within that surface. A hole is represented by an interior ring within the corresponding surface geometry object.

Using an interior hole poylgon is therefore only required if the opening is completely inside the exterior ring of the embracing boundary surface polygon. This is not the case in your example because your wall surfaces are triangulated and hence, as you write, opening geometries might overlap with two or more triangles. In such cases, simply cut the opening geometry from all overlapping triangles. So, instead of creating an interior polygon, adapt the exterior rings of the triangles such that they do not overlap with the opening anymore.

Well, there is another issue in your model. Each and every triangle is semantically classified as individual `WallSurface` object. But also in real world you wouldn't say that the building is made of triangular walls, right? So, you should rather use one `WallSurface` object for each main facade of the building (in your example, there should be six `WallSurface` objects + one `GroundSurface` at the bottom and one `RoofSurface` at the top). You can still use triangles to describe the geometry of each `WallSurface` object because the geometry is given as `gml:MultiSurface` which can contain as many triangles as you wish. 

If you change the semantics in this way, then you will also have a clear 1:1 relationship between a `Window` or `Door` object and its embracing `WallSurface` object.

Hope this helps. There is also an informal [modelling guideline for CityGML buildings](http://en.wiki.quality.sig3d.org/index.php/Modeling_Guide_for_3D_Objects_-_Part_2:_Modeling_of_Buildings_(LoD1,_LoD2,_LoD3)). It is not an official OGC document but rather a collection of best practices. Check [this chapter](http://en.wiki.quality.sig3d.org/index.php/Modeling_Guide_for_3D_Objects_-_Part_2:_Modeling_of_Buildings_(LoD1,_LoD2,_LoD3)#Wall_Surfaces_.28bldg:WallSurface.29) on wall surfaces. The guideline also recommends to use one `WallSurface` object per wall element of the building.

**Comment by fredpeertje** [comment]
Thank you for the detailed explanation and references!

With “adapt”, do you mean combining two wall surface members (linearRing) that intersect with one window? Like if you have two adjacent linearRings in counter-clockwise order, merge these values to one linearRing? I tried this manually (not automatically) and the result can be seen in the image for two windows. 

<img width="495" alt="Schermafbeelding 2020-09-01 om 19 36 42" src="https://user-images.githubusercontent.com/64864465/91887135-ab315380-ec8a-11ea-8b9f-2e3cca8b8d79.png">

**Comment by clausnagel** [comment]
If merging the triangles to larger polygons works for you and the resulting geometry is valid, then this is definetly a possible solution.

We agree that in case the opening polygon is not completely inside a single wall polygon, cutting a hole (interior ring) is not feasible. So, what I meant is that if the opening polygon overlaps with two or more wall polygons, it should be subtracted from each wall polygon. This changes the exterior rings of the wall polygons. 

I tried to create some figures. Below you see two polygons P1 and P2. 

![step1](https://user-images.githubusercontent.com/5517439/92239861-f8e0d280-eebb-11ea-96f3-05793521fa6f.png)

Now we add a window poylgon to the figure that overlaps with P1 and P2.

![step2](https://user-images.githubusercontent.com/5517439/92239863-f8e0d280-eebb-11ea-8ce9-291fd8094a1a.png)

Creating holes in P1 and P2 as suggested in your initial post is not possible in this case. But what you can do is to substract the window polygon from both P1 and P2. This will change their exterior rings as shown below. 

![step3](https://user-images.githubusercontent.com/5517439/92239865-f9796900-eebb-11ea-8e0c-f76a05bd59f8.png)

And, finally, the exploded view below illustrates P1 and P2 after the subtract operation. As you can see, they do not have holes.

![step4](https://user-images.githubusercontent.com/5517439/92239866-f9796900-eebb-11ea-83ac-13d7c28e6692.png)

Hope this helps.

**Comment by fredpeertje** [comment]
I partly solved the issue by writing an algorithm that combines two adjacent polygons by finding a common edge and remove it. 

I also tried to implement the solution you proposed, which I think would be a better solution. However, to the best of my knowledge, this can be achieved in 2D, but in 3D this will be pretty difficult.
