### ISSUE TITLE
building v3.0.0-rc.3 fails

### ISSUE THREAD

**Issue by b-schwab** [citygml4j/citygml4j#33]
Hi Claus,

first of all: Great library, many thanks!

I'm currently updating my project to v3.0.0-rc.3 and I noticed that building citygml4j & samples on the citygml3-devel branch doesn't work in my environment. Please have a look into this [build run](https://github.com/b-schwab/citygml4j/runs/4924510414?check_suite_focus=true#step:5:21).
Some classes of gml-objects (e.g. `VisitableGeometry`,  `ResolvableAssociation`) are not found and I assume that `gml-objects:1.0.0-SNAPSHOT` was released earlier than the implementation of those classes.

Best regards
Benedikt

P.S.: If you are interested, I can create a PR for the [build workflow](https://github.com/b-schwab/citygml4j/blob/build-workflow/.github/workflows/build-citygml4j.yml).

**Comment by clausnagel** [comment]
Thanks for pointing me to this issue, @b-schwab. I have been working on `citygml3-devel` and its dependencies `gml-objects`, `xal-objects` and `xml-objects` lately. Obviously, I have linked v3.0.0-rc.3 against the v1.0.0-SNAPSHOT version of these dependencies instead of creating explicit and stable tags for them. Sorry for any inconvience, my bad.

You can now build the `citygml3-devel` branch again, while v3.0.0-rc.3 is unfortunately broken.

The build workflow is indeed interesting and a PR is very welcome. This repo is still in a transition state from version 2 and 3, so maybe we should wait until version 3 has been released?!

**Comment by b-schwab** [comment]
Thank you for your very fast help @clausnagel! No need to apologize, it is a RC after all.

You fixed the problem, citygml4j on the `citygml3-devel` branch is [building](https://github.com/b-schwab/citygml4j/runs/4927655099?check_suite_focus=true) and the samples are running locally.

I also experimented a bit with [jitpack.io](https://jitpack.io/) (an on-demand package manager) and got the jar distribution for my citygml4j fork on the `enable-jitpack` branch up working (only a little [configuration file](https://github.com/b-schwab/citygml4j/blob/enable-jitpack/jitpack.yml) + skipping the signing process was needed). Other projects can depend on this jar now. For me, this is a temporary solution until the official transition is complete.

Regarding the PR: I could restrict the build workflow to run only on the `citygml3-devel` branch and I would create the PR when it suits you best in the development phase.
Moreover, Jitpack provides a lot of flexibility. If it could be helpful for you as well, I can prepare a PR, too.

Best regards
Benedikt

**Comment by clausnagel** [comment]
Great, please go ahead with the PRs

**Comment by b-schwab** [comment]
Just created the PRs.
Many thanks for solving, @clausnagel.
